name: prettier and build and packr2
on:
 push:
    branches:
      - master

jobs:
  lint:
    name: build 
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'
      - run: go install github.com/gobuffalo/packr/v2/packr2
      - name: build and push automatic fixes
        run: |
          cd ./frontend/app && npm i --legacy-peer-deps && CI=false npm run build && cd .. && packr2 
          cd app && npm run prettier
          git config user.name 'Github Actions'
          git config user.email github-actions@github.com
          cd ..
          git add ./packrd/packed-packr.go
          cd app && git add .
          git commit -m "[skip ci] Automatic build fixes" || echo -n
          git push


