name: PRCheck
on:
  pull_request:
    branches:
      - master
jobs:
  eslint:
    name: ESLint Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Eslint
        run: yarn --cwd ./frontend/app run lint
  test:
    name: Test Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Tests
        run: NODE_OPTIONS="--max_old_space_size=8192" yarn --cwd ./frontend/app run test
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Go Test
        run: go test -v ./...

  build:
    name: Build Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Build 
        run: CI=false yarn --cwd ./frontend/app run build

  prettier:
    name: Prettier Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Prettier 
        run: CI=false yarn --cwd ./frontend/app run prettier:check 


  test-jest:
    name: Test Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Tests
        run: NODE_OPTIONS="--max_old_space_size=8192" yarn --cwd ./frontend/app run test-jest

