name: PRCheck
on:
  pull_request:
    branches:
      - master
jobs:
  eslint:
    name: ESLint Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Eslint
        run: yarn --cwd ./frontend/app run lint
  test:
    name: Test Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Tests
        run: yarn --cwd ./frontend/app run test
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Go Test
        run: go test -v ./...
   
  build:
    name: build Job
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Eslint
        run: yarn --cwd ./frontend/app run build
